name: Build (Not Working Icon)
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: '0.0.0'

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Ahk2Exe
        run: |
          .\build_not_working.ps1
        
      - uses: actions/upload-artifact@v4
        with:
          name: 'NotWorking.exe'
          path: '${{ github.workspace }}\NotWorking.exe'
